server:
  port: 5050

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/MigrationDemo
    username: postgres
    password: 50145014
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



